# Generated by Django 2.1.1 on 2019-01-25 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20190124_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis_datos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('precio_compra', models.PositiveIntegerField(default=0, verbose_name='Precio Compra')),
                ('precio_venta', models.PositiveIntegerField(default=0, verbose_name='Precio Venta')),
                ('precio_estimado_15', models.PositiveIntegerField(default=0, verbose_name='Precio Venta con 15%')),
                ('precio_estimado_30', models.PositiveIntegerField(default=0, verbose_name='Precio Venta con 30%')),
                ('ganancia_estimada_15', models.PositiveIntegerField(default=0, verbose_name='Ganancia por productos con 15%')),
                ('ganacia_estimada_30', models.PositiveIntegerField(default=0, verbose_name='Ganancia por productos con 30%')),
                ('total_producto', models.PositiveIntegerField(default=0, verbose_name='Total valor del producto')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de Creacion')),
                ('local', models.CharField(blank=True, max_length=100, null=True, verbose_name='Local')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Productos')),
            ],
            options={
                'verbose_name': 'Analisis de Datos',
                'verbose_name_plural': 'Analisis de Datos',
            },
        ),
    ]
