# Generated by Django 2.1.1 on 2019-01-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_analisis_datos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analisis_datos',
            old_name='precio_venta',
            new_name='precio_venta_actual',
        ),
        migrations.RenameField(
            model_name='analisis_datos',
            old_name='total_producto',
            new_name='total_producto_actual',
        ),
        migrations.AddField(
            model_name='analisis_datos',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado del producto'),
        ),
        migrations.AddField(
            model_name='analisis_datos',
            name='ganancia_precio_actual',
            field=models.PositiveIntegerField(default=0, verbose_name='Ganancia por productos actual'),
        ),
    ]
