# Generated by Django 2.1.2 on 2019-01-27 04:21

from django.db import migrations, models
import productos.models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20190125_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=productos.models.custom_upload_to),
        ),
    ]
