# Generated by Django 2.1.2 on 2019-01-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
