# Generated by Django 2.1.2 on 2019-02-02 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_auto_20190130_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='fecha_actualizacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Actualizacion'),
        ),
        migrations.AlterField(
            model_name='analisis_datos',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Estado del producto'),
        ),
    ]
