# Generated by Django 2.1.2 on 2019-02-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_auto_20190201_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, default='/media/core/sin-imagen.png', null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
    ]
