# Generated by Django 2.1.2 on 2019-02-06 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_auto_20190206_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Categorias'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio_compra',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Precio compra'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio_venta',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Precio venta'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='promocion',
            field=models.TextField(blank=True, null=True, verbose_name='Promocion'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unidad de Medida'),
        ),
    ]
