# Generated by Django 2.1.2 on 2019-02-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_auto_20190206_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidades_Medidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida', models.CharField(max_length=50, verbose_name='Medida')),
            ],
            options={
                'verbose_name': 'Unidades de Medida',
                'verbose_name_plural': 'Unidades de Medidas',
                'ordering': ['medida'],
            },
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, default='core/sin-imagen.png', null=True, upload_to='productos/'),
        ),
    ]
