# Generated by Django 2.1.2 on 2019-02-06 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_auto_20190206_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Unidades_Medidas'),
        ),
    ]
