# Generated by Django 2.1.2 on 2019-02-10 19:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_auto_20190206_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='promocion',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Promocion'),
        ),
    ]
