# Generated by Django 2.1.2 on 2019-03-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_auto_20190210_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='promocion',
            field=models.TextField(blank=True, null=True, verbose_name='Promocion'),
        ),
    ]
