# Generated by Django 2.1.1 on 2019-01-21 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lista_compra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista_Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total_lista', models.IntegerField(default=0)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lista_compra.Locales')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista de compras',
                'verbose_name_plural': 'Listas de compras',
                'db_table': 'Lista_Compra',
                'ordering': ['-fecha'],
            },
        ),
    ]
