# Generated by Django 2.1.1 on 2019-01-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_compra', '0002_lista_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_compra',
            name='total_lista',
            field=models.IntegerField(default=0, verbose_name='Total'),
        ),
    ]
