# Generated by Django 2.1.2 on 2019-02-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_compra', '0003_auto_20190122_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='locales',
            name='logo',
            field=models.ImageField(blank=True, default='/media/lista_compra/sin_logo.png', null=True, upload_to='lista_compra/'),
        ),
    ]
