# Generated by Django 2.1.2 on 2019-02-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_compra', '0004_locales_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locales',
            name='logo',
            field=models.ImageField(blank=True, default='/media/core/sin-imagen.png', null=True, upload_to='lista_compra/'),
        ),
    ]
