# Generated by Django 2.1.2 on 2019-02-06 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lista_compra', '0005_auto_20190206_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_compra',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lista_compra.Locales'),
        ),
        migrations.AlterField(
            model_name='lista_compra',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
    ]
