# Generated by Django 2.1.1 on 2019-01-22 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('lista_compra', '0003_auto_20190122_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos_Comprar_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='cantidad')),
                ('total_producto', models.PositiveIntegerField(default=0, verbose_name='total')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='comentarios')),
                ('cod_lista_compras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lista_compra.Lista_Compra')),
                ('cod_productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Productos')),
            ],
            options={
                'verbose_name': 'Producto a Comprar',
                'verbose_name_plural': 'Productos a Comprar',
                'db_table': 'Productos_Comprar',
                'ordering': ['cod_productos__nombre'],
            },
        ),
    ]
