# Generated by Django 2.1.1 on 2019-01-22 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos_comprar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos_comprar_model',
            options={'verbose_name': 'Producto a Comprar', 'verbose_name_plural': 'Productos a Comprar'},
        ),
    ]
