# Generated by Django 2.1.2 on 2019-01-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_comprar', '0002_auto_20190122_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos_comprar_model',
            name='estado_producto',
            field=models.BooleanField(default=False, verbose_name='Estado del Producto'),
        ),
    ]
