# Generated by Django 2.1.2 on 2019-02-07 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos_comprar', '0003_productos_comprar_model_estado_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos_comprar_model',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='productos_comprar_model',
            name='cod_productos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Productos'),
        ),
    ]
