# Generated by Django 2.1.2 on 2019-03-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inicio_banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner1', models.ImageField(default='core/banner/carousel1.jpg', upload_to='core/banner/', verbose_name='Banner 1')),
                ('banner_titulo1', models.CharField(default='Titulo 1', max_length=100, verbose_name='Titulo del banner 1')),
                ('banner_subtitulo1', models.CharField(default='Mensaje 1', max_length=100, verbose_name='Subtitulo del banner 1')),
                ('banner2', models.ImageField(default='core/banner/carousel2.jpg', upload_to='core/banner/', verbose_name='Banner 2')),
                ('banner_titulo2', models.CharField(default='Titulo 2', max_length=100, verbose_name='Titulo del banner 2')),
                ('banner_subtitulo2', models.CharField(default='Mensaje 2', max_length=100, verbose_name='Subtitulo del banner 2')),
                ('banner3', models.ImageField(default='core/banner/carousel3.jpg', upload_to='core/banner/', verbose_name='Banner 3')),
                ('banner_titulo3', models.CharField(default='Titulo 3', max_length=100, verbose_name='Titulo del banner 3')),
                ('banner_subtitulo3', models.CharField(default='Mensaje 3', max_length=100, verbose_name='Subtitulo del banner 3')),
            ],
            options={
                'verbose_name': 'Inicio Banner',
            },
        ),
    ]
