# Generated by Django 2.1.2 on 2019-03-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inicio_banner',
            options={'ordering': ['id'], 'verbose_name': 'Inicio Banner', 'verbose_name_plural': 'Inicio Banners'},
        ),
        migrations.AddField(
            model_name='inicio_banner',
            name='activado',
            field=models.BooleanField(default=False, verbose_name='Banners Activados?'),
        ),
    ]
