# Generated by Django 2.1.2 on 2019-03-04 15:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20190304_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inicio_circulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circulo1_titulo', models.CharField(default='Siempre Fresco', max_length=100, verbose_name='Titulo de 1° Circulo')),
                ('circulo1_contenido', ckeditor.fields.RichTextField(blank=True, max_length=200, null=True, verbose_name='Contenido de 1° Circulo')),
                ('circulo2_titulo', models.CharField(default='Mejores Precios', max_length=100, verbose_name='Titulo de 2° Circulo')),
                ('circulo2_contenido', ckeditor.fields.RichTextField(blank=True, max_length=200, null=True, verbose_name='Contenido de 2° Circulo')),
                ('circulo3_titulo', models.CharField(default='Buena Calidad', max_length=100, verbose_name='Titulo de 3° Circulo')),
                ('circulo3_contenido', ckeditor.fields.RichTextField(blank=True, max_length=200, null=True, verbose_name='Contenido de 3° Circulo')),
                ('activado', models.BooleanField(default=False, verbose_name='Conjunto Activado')),
            ],
            options={
                'verbose_name': 'Conjunto de Circulo',
                'verbose_name_plural': 'Conjunto de Circulos',
            },
        ),
        migrations.CreateModel(
            name='Inicio_titulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_principal', models.CharField(default='Bienvenido al local de la Sra. Ines', max_length=200, verbose_name='Titulo Principal')),
                ('subtitulo_principal', models.CharField(default='Donde siempre tenemos de todo un poco', max_length=200, verbose_name='Subtitulo Principal')),
                ('activado', models.BooleanField(default=False, verbose_name='Conjunto Activado')),
            ],
            options={
                'verbose_name': 'Titulo de Inicio',
                'verbose_name_plural': 'Titulo de Inicio',
            },
        ),
        migrations.AlterField(
            model_name='inicio_banner',
            name='activado',
            field=models.BooleanField(default=False, verbose_name='Conjunto Activado'),
        ),
    ]
