# Generated by Django 2.1.2 on 2019-03-04 16:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20190304_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inicio_cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_cards', models.CharField(default='Creemos en', max_length=100, verbose_name='Titulo de las Cards')),
                ('img_card1', models.ImageField(default='core/index/muestra1.JPG', upload_to='core/index/', verbose_name='Imagen de Card 1')),
                ('titulo_card1', models.CharField(default='Card Title 1', max_length=200, verbose_name='Titulo de Card 1')),
                ('contenido_card1', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido de Card 1')),
                ('img_card2', models.ImageField(default='core/index/muestra2.JPG', upload_to='core/index/', verbose_name='Imagen de Card 2')),
                ('titulo_card2', models.CharField(default='Card Title 2', max_length=200, verbose_name='Titulo de Card 2')),
                ('contenido_card2', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido de Card 2')),
                ('img_card3', models.ImageField(default='core/index/muestra3.JPG', upload_to='core/index/', verbose_name='Imagen de Card 3')),
                ('titulo_card3', models.CharField(default='Card Title 3', max_length=200, verbose_name='Titulo de Card 3')),
                ('contenido_card3', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido de Card 3')),
                ('img_card4', models.ImageField(default='core/index/muestra4.png', upload_to='core/index/', verbose_name='Imagen de Card 4')),
                ('titulo_card4', models.CharField(default='Card Title 4', max_length=200, verbose_name='Titulo de Card 4')),
                ('contenido_card4', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido de Card 4')),
                ('activado', models.BooleanField(default=False, verbose_name='Conjunto Activado')),
            ],
            options={
                'verbose_name': 'Conjunto de Card',
                'verbose_name_plural': 'Conjunto de Cards',
            },
        ),
        migrations.CreateModel(
            name='Inicio_foto_final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_foto_final', models.ImageField(default='core/index/imb-botom.JPG', upload_to='core/index/', verbose_name='Imagen de la foto del final')),
                ('titulo_foto_final', models.CharField(default='Card Title Final Photo', max_length=200, verbose_name='Titulo de la foto del final')),
                ('contenido_foto_final', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido de la foto del final')),
            ],
            options={
                'verbose_name': 'Conjunto de la Foto Final',
                'verbose_name_plural': 'Conjunto de la Foto Final',
            },
        ),
    ]
