# Generated by Django 2.1.2 on 2019-03-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_inicio_cards_inicio_foto_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='inicio_foto_final',
            name='activado',
            field=models.BooleanField(default=False, verbose_name='Conjunto Activado'),
        ),
    ]
