# Generated by Django 2.1.2 on 2019-03-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_inicio_foto_final_activado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(default='Jose Miguel Carrera 1997, Macul', max_length=200, verbose_name='Direccion')),
                ('contacto', models.CharField(default='(02) 28232003', max_length=100, verbose_name='Contacto')),
                ('email', models.CharField(default='oavr.18@gmail.com', max_length=100, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='Productos_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_list', models.CharField(default='Productos', max_length=200, verbose_name='Titulo de Productos')),
                ('subtitulo_list', models.CharField(blank=True, max_length=300, null=True, verbose_name='Subtitulo de Productos')),
            ],
            options={
                'verbose_name': 'Productos Listar',
                'verbose_name_plural': 'Productos Listar',
            },
        ),
    ]
