# Generated by Django 2.1.2 on 2019-03-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_footer_productos_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='activado',
            field=models.BooleanField(default=False, verbose_name='Conjunto Activado'),
        ),
        migrations.AddField(
            model_name='productos_list',
            name='activado',
            field=models.BooleanField(default=False, verbose_name='Conjunto Activado'),
        ),
    ]
