# Generated by Django 2.1.2 on 2019-03-05 03:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20190304_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='quiero_comprar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='¿Quieres comprar?', max_length=200, verbose_name='Titulo de Quiero comprar')),
                ('subtitulo', models.CharField(default='Aqui te diremos como puedes comprar, donde nos ubicamos y los medios de forma de pago.', max_length=300, verbose_name='Subtitulo de Quiero comprar')),
                ('titulo_card1', models.CharField(default='Como comprar', max_length=200, verbose_name='Titulo de 1° Card')),
                ('contenido_card1', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido de 1° Card')),
                ('titulo_card2', models.CharField(default='Donde nos ubicamos', max_length=200, verbose_name='Titulo de 2° Card')),
                ('contenido_card2', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido de 2° Card')),
                ('titulo_card3', models.CharField(default='Medios de pago', max_length=200, verbose_name='Titulo de 3° Card')),
                ('contenido_card3', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido de 3° Card')),
                ('activado', models.BooleanField(default=False, verbose_name='Conjunto Activado')),
            ],
            options={
                'verbose_name': 'Quiero Comprar',
                'verbose_name_plural': 'Quiero Comprar',
            },
        ),
    ]
